#!/usr/bin/env node
/* eslint-disable */
const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");

const ROOT = path.resolve(__dirname, "..");
const ARTICLES_DIR = path.join(ROOT, "content", "articles");
const PUBLIC_DIR = path.join(ROOT, "public");
const OUT_FILE = path.join(ROOT, "src", "data", "articles.generated.ts");

const INLINE_SVG_RE = /<inline-svg\s+src="([^"]+)"\s*\/?>(\s*<\/inline-svg>)?/g;

function computeReadingMinutes(markdown) {
  let text = markdown;

  let codeLines = 0;
  text = text.replace(/```[^\n]*\n([\s\S]*?)```/g, (_m, code) => {
    codeLines += code.split("\n").filter((l) => l.trim().length > 0).length;
    return "";
  });

  const imageCount = (text.match(/!\[[^\]]*\]\([^)]+\)/g) || []).length;
  const svgCount = (text.match(/<inline-svg\b[^>]*>/g) || []).length;
  const mediaCount = imageCount + svgCount;

  text = text.replace(/!\[[^\]]*\]\([^)]+\)/g, "");
  text = text.replace(/<inline-svg\b[^>]*\/?>/g, "");
  text = text.replace(/<[^>]+>/g, "");

  const words = (text.match(/[a-zA-Zа-яА-ЯёЁ\d]+/g) || []).length;

  const proseSeconds = (words / 180) * 60;
  const codeSeconds = codeLines * 3;
  const mediaSeconds = mediaCount * 10;
  const total = proseSeconds + codeSeconds + mediaSeconds;
  return Math.max(1, Math.ceil(total / 60));
}

function inlineSvgs(body, sourceFile) {
  return body.replace(INLINE_SVG_RE, (_match, src) => {
    const relPath = src.replace(/^\//, "");
    const filePath = path.join(PUBLIC_DIR, relPath);
    if (!fs.existsSync(filePath)) {
      throw new Error(`inline-svg: file not found "${src}" (referenced from ${sourceFile})`);
    }
    let svg = fs.readFileSync(filePath, "utf8");
    svg = svg.replace(/^﻿/, "").replace(/^<\?xml[^?]*\?>\s*/, "").trim();
    return svg;
  });
}

function readArticles() {
  if (!fs.existsSync(ARTICLES_DIR)) return [];
  return fs
    .readdirSync(ARTICLES_DIR)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const full = path.join(ARTICLES_DIR, file);
      const raw = fs.readFileSync(full, "utf8");
      const { data, content } = matter(raw);
      const slug = (data.slug || file.replace(/\.md$/, "")).trim();
      const title = (data.title || slug).toString();
      const dateValue = data.date;
      if (!dateValue) {
        throw new Error(`Article "${file}" is missing required "date" in frontmatter`);
      }
      const date = dateValue instanceof Date
        ? dateValue.toISOString().slice(0, 10)
        : String(dateValue).slice(0, 10);
      const trimmedContent = content.trim();
      const body = inlineSvgs(trimmedContent, file);
      const explicit = data.readingMinutes ?? data.reading_time;
      const readingMinutes =
        typeof explicit === "number" && explicit > 0
          ? Math.round(explicit)
          : computeReadingMinutes(trimmedContent);
      return { slug, title, date, body, readingMinutes };
    })
    .sort((a, b) => b.date.localeCompare(a.date));
}

function generate(articles) {
  const header = `// AUTO-GENERATED by scripts/build-content.js. Do not edit by hand.
// Source: content/articles/*.md
// Run \`npm run content:build\` to regenerate.

export type GeneratedArticle = {
  type: "article";
  slug: string;
  title: string;
  date: string;
  body: string;
  readingMinutes: number;
};

export const generatedArticles: GeneratedArticle[] = `;
  const payload = articles.map((a) => ({
    type: "article",
    slug: a.slug,
    title: a.title,
    date: a.date,
    body: a.body,
    readingMinutes: a.readingMinutes,
  }));
  return header + JSON.stringify(payload, null, 2) + ";\n";
}

function build() {
  const articles = readArticles();
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  const next = generate(articles);
  const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : null;
  if (prev === next) return;
  fs.writeFileSync(OUT_FILE, next, "utf8");
  console.log(`[content] generated ${articles.length} article(s) -> ${path.relative(ROOT, OUT_FILE)}`);
}

build();

if (process.argv.includes("--watch")) {
  const IMAGES_DIR = path.join(PUBLIC_DIR, "images");
  console.log(`[content] watching ${path.relative(ROOT, ARTICLES_DIR)} and ${path.relative(ROOT, IMAGES_DIR)} ...`);
  let pending;
  const onChange = () => {
    clearTimeout(pending);
    pending = setTimeout(() => {
      try {
        build();
      } catch (err) {
        console.error("[content] build failed:", err.message);
      }
    }, 100);
  };
  fs.watch(ARTICLES_DIR, { persistent: true }, onChange);
  if (fs.existsSync(IMAGES_DIR)) {
    fs.watch(IMAGES_DIR, { persistent: true }, onChange);
  }
}
